# Generated by Django 5.0 on 2023-12-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='fixed_at',
            new_name='updated_at',
        ),
    ]
